<a href="https://colab.research.google.com/github/silvianecunha/pantanal/blob/main/dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
# dados = '/home/silviane/Documentos/4 -Esalq/Artigo_SBAI/consisted_data.csv'
dados = 'consisted_data.csv'

In [6]:
df = pd.read_csv(dados)
df = pd.DataFrame(df)
df.set_index(['Date'])
df.head()

         Date  IMERG: 1754000  ...  Gauge: 02157004  Gauge: 01955000
0  02/06/2000             0.0  ...              0.0              0.0
1  03/06/2000             0.0  ...             72.0              3.0
2  04/06/2000             0.0  ...             14.1              4.3
3  05/06/2000             0.0  ...              0.0              0.0
4  06/06/2000             0.0  ...              0.0              0.0

[5 rows x 249 columns]